apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: Example-Repo-Catalog-Info
spec:
  type: url
  targets:
    - https://github.com/guohui-gao/backstage-examples/blob/main/entities.yaml
    - https://github.com/guohui-gao/backstage-examples/blob/main/org.yaml
    #- https://github.com/guohui-gao/backstage-examples/blob/main/entities.yaml
    - https://github.com/guohui-gao/backstage-examples/blob/main/templates/template.yaml
    #- https://github.com/guohui-gao/backstage-examples/blob/main/templates/spring-boot-template.yaml
