apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstageexample
  description: |
    description of the repo
spec:
  type: service
  owner: user:guest
  lifecycle: experimental

apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: location
  description: |
    location
spec:
  targets:: 
    - org.yaml
    - entities.yaml
